import test from 'node:test';import assert from 'node:assert/strict';
import {story} from '../src/story.mjs';import {clamp,range,ease,progressFor,sceneState,seeded,beatOpacity} from '../src/math.mjs';import {train,radio,dome,pines,stars} from '../src/illustrations.mjs';
test('story is a complete seven-chapter Russian journey',()=>{assert.deepEqual(story.chapters.map(c=>c.id),['departure','window','tunnel','arrival','receiver','sky','dawn']);assert.equal(story.author,'IseFDK');assert.equal(new Set(story.chapters.map(c=>c.id)).size,7);for(const c of story.chapters){assert.equal(c.paragraphs.length,3);assert.ok(c.paragraphs.every(p=>p.split(/\s+/).length>=40));assert.match(c.time,/^\d\d:\d\d$/)}assert.ok(story.epilogue.length>35);assert.match(story.note,/вымышлены/)});
test('word count supports the promised five-minute read',()=>{let n=story.chapters.flatMap(c=>c.paragraphs).join(' ').split(/\s+/).length;assert.ok(n>=950&&n<=1200)});
test('chapter clock moves forward',()=>{let last=0;for(const c of story.chapters){let [h,m]=c.time.split(':').map(Number),now=h*60+m;assert.ok(now>last);last=now}});
test('scroll progress clamps outside chapters and handles short heights',()=>{assert.equal(progressFor(-20,0,4000,1000),0);assert.equal(progressFor(1500,0,4000,1000),.5);assert.equal(progressFor(8000,0,4000,1000),1);assert.ok(Number.isFinite(progressFor(1,0,100,1000)))});
test('smooth ranges are finite and reversible without accumulated state',()=>{assert.equal(clamp(-3),0);assert.equal(clamp(2),1);assert.ok(Math.abs(range(.4,.2,.6)-.5)<1e-10);assert.equal(ease(0),0);assert.equal(ease(1),1);for(const p of [0,.25,.5,.75,1])assert.equal(ease(p),1-ease(1-p))});
test('all scenes support forward, reverse and chapter jumps deterministically',()=>{for(const c of story.chapters){const initial=sceneState(0,c.id);for(const p of [0,.1,.9,1,.5,0])for(const v of Object.values(sceneState(p,c.id)))assert.ok(Number.isFinite(v));assert.deepEqual(sceneState(0,c.id),initial);assert.deepEqual(sceneState(1.5,c.id),sceneState(1,c.id))}});
test('train, shutter, needle and dawn motions reach intended ending',()=>{assert.ok(sceneState(1,'departure').trainX<-90);assert.equal(sceneState(1,'sky').opening,100);assert.ok(sceneState(1,'receiver').glow>=1);assert.equal(sceneState(1,'dawn').zoom,1)});
test('illustrations are original deterministic inline SVG',()=>{for(const f of [train,radio,dome,pines,stars]){assert.match(f(),/^<svg /);assert.ok(!f().includes('<script'));assert.equal(f(),f())}assert.match(train(),/train-body/);assert.match(radio(),/tuning-knob/);assert.match(dome(),/shutter-left/)});
test('art seeding is reproducible',()=>{const a=seeded(52),b=seeded(52);for(let i=0;i<30;i++)assert.equal(a(),b())});

test('visual story beats never ghost over each other',()=>{for(let i=0;i<=10000;i++){const p=i/10000,visible=[0,1,2].filter(j=>beatOpacity(p,j)>0);assert.ok(visible.length<=1,`Overlapping beats at ${p}`)}for(const p of [.32,.56,.82])assert.ok([0,1,2].some(j=>beatOpacity(p,j)===1))});
test('full-scene forest artwork is bottom-aligned and covers its scene',()=>{assert.match(pines(),/preserveAspectRatio="xMidYMax slice"/);assert.match(stars(),/preserveAspectRatio="xMidYMax slice"/)});
